// Food Profile Object based on Java Enums - Updated to match current interface
export const foodProfile = {
  foodPreferences: {
    foodAllergies: [
      "PEANUTS",
      "TREE_NUTS",
      "MILK",
      "EGGS",
      "WHEAT",
      "SOY",
      "FISH",
      "SHELLFISH",
      "SESAME",
      "CORN",
      "SULFITES",
      "MUSTARD",
      "CELERY",
      "LUPIN",
      "MOLLUSKS",
    ],
    // Removed cuisinePreferences from foodPreferences (moved to flavorProfile)
    // Removed favouriteIngredients and ingredientsToAvoid (these are now typed inputs)
  },
  cookingProfile: {
    cookingSkillLevel: [
      "BEGINNER",
      "NOVICE",
      "INTERMEDIATE",
      "ADVANCED",
      "EXPERT",
      "PROFESSIONAL",
    ],
    cookingEquipment: [
      "BASIC_STOVE",
      "OVEN",
      "MICROWAVE",
      "AIR_FRYER",
      "SLOW_COOKER",
      "PRESSURE_COOKER",
      "GRILL",
      "BLENDER",
      "FOOD_PROCESSOR",
      "STAND_MIXER",
      "RICE_COOKER",
      "TOASTER_OVEN",
      "SOUS_VIDE",
      "DEEP_FRYER",
      "STEAMER",
      "BREAD_MAKER",
      "JUICER",
      "ESPRESSO_MACHINE",
    ],
    cookingTimePreference: [
      "UNDER_15_MINUTES",
      "MINUTES_15_30",
      "MINUTES_30_45",
      "MINUTES_45_60",
      "HOUR_1_2",
      "HOURS_2_4",
      "OVER_4_HOURS",
    ],
    budgetConsiderations: [
      "VERY_LOW",
      "LOW",
      "MODERATE",
      "HIGH",
      "LUXURY",
      "NO_BUDGET_LIMIT",
    ],
  },
  advancedOptions: {
    nutritionalGoals: [
      "WEIGHT_LOSS",
      "WEIGHT_GAIN",
      "MUSCLE_BUILDING",
      "MAINTENANCE",
      "HIGH_PROTEIN",
      "LOW_CALORIE",
      "HIGH_FIBER",
      "HEART_HEALTHY",
      "BONE_HEALTH",
      "BRAIN_HEALTH",
      "ENERGY_BOOST",
      "IMMUNE_SUPPORT",
      "DIGESTIVE_HEALTH",
      "ANTI_INFLAMMATORY",
      "DETOX",
      "BALANCED_NUTRITION",
    ],
    // Removed foodDeliveryApps, groceryShoppingTypes, heritageCoking
    // (these don't exist in your current AdvancedOptions interface)
  },
  flavorProfile: {
    cuisinePreferences: [
      "AMERICAN",
      "ITALIAN",
      "CHINESE",
      "JAPANESE",
      "MEXICAN",
      "INDIAN",
      "FRENCH",
      "THAI",
      "GREEK",
      "MEDITERRANEAN",
      "KOREAN",
      "SPANISH",
      "MIDDLE_EASTERN",
      "VIETNAMESE",
      "GERMAN",
      "BRITISH",
      "BRAZILIAN",
      "MOROCCAN",
      "ETHIOPIAN",
      "CARIBBEAN",
      "FUSION",
      "INTERNATIONAL",
    ],
    spicinessLevel: ["MILD", "MEDIUM", "HOT", "VERY_HOT", "EXTREMELY_HOT"],
    tastePreferences: ["SWEET", "SALTY", "SOUR", "BITTER", "UMAMI", "SPICY"],
  },
};
