/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdvancedFeatures: typeof import('./components/user-profile/AdvancedOptions.vue')['default']
    AdvancedFeaturesEdit: typeof import('./components/user-profile/AdvancedOptionsEdit.vue')['default']
    AdvancedOptions: typeof import('./components/user-profile/AdvancedOptions.vue')['default']
    AdvancedOptionsEdit: typeof import('./components/user-profile/AdvancedOptionsEdit.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ApplicationCard: typeof import('./components/ApplicationCard.vue')['default']
    ApplicationsWrapper: typeof import('./components/my-applications/ApplicationsWrapper.vue')['default']
    ApplicationsWrapperAdmin: typeof import('./components/my-applications/ApplicationsWrapperAdmin.vue')['default']
    AppNavbar: typeof import('./components/AppNavbar.vue')['default']
    AppSidebar: typeof import('./components/AppSidebar.vue')['default']
    CookingProfile: typeof import('./components/user-profile/CookingProfile.vue')['default']
    CookingProfileEdit: typeof import('./components/user-profile/CookingProfileEdit.vue')['default']
    CreateApplicationPanel: typeof import('./components/off-canvas/CreateApplicationPanel.vue')['default']
    FileListItem: typeof import('./components/FileListItem.vue')['default']
    FlavorProfile: typeof import('./components/user-profile/FlavorProfile.vue')['default']
    FlavorProfileEdit: typeof import('./components/user-profile/FlavorProfileEdit.vue')['default']
    FoodPreferences: typeof import('./components/user-profile/FoodPreferences.vue')['default']
    FoodPreferenceSection: typeof import('./components/user-profile/FoodPreferenceSection.vue')['default']
    FoodPreferencesEdit: typeof import('./components/user-profile/FoodPreferencesEdit.vue')['default']
    FoodProfileEdit: typeof import('./components/off-canvas/FoodProfileEdit.vue')['default']
    GlobalOffCanvas: typeof import('./components/GlobalOffCanvas.vue')['default']
    LoadingSpinner: typeof import('./components/LoadingSpinner.vue')['default']
    LoginCard: typeof import('./components/LoginCard.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    NikolakisCard: typeof import('./components/NikolakisCard.vue')['default']
    NoDataMessage: typeof import('./components/NoDataMessage.vue')['default']
    Notification: typeof import('./components/NotificationItem.vue')['default']
    NotificationAlert: typeof import('./components/NotificationAlert.vue')['default']
    NotificationItem: typeof import('./components/NotificationItem.vue')['default']
    NotificationWrapper: typeof import('./components/off-canvas/NotificationWrapper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceCard: typeof import('./components/ServiceCard.vue')['default']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    SignupCard: typeof import('./components/SignupCard.vue')['default']
    UserInfoEdit: typeof import('./components/off-canvas/UserInfoEdit.vue')['default']
    UserProfileEdit: typeof import('./components/off-canvas/UserProfileEdit.vue')['default']
    UserProfileInfoEdit: typeof import('./components/user-profile/UserProfileInfoEdit.vue')['default']
    ViewApplicationPanel: typeof import('./components/off-canvas/ViewApplicationPanel.vue')['default']
  }
}
