/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    'dashboard': RouteRecordInfo<'dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'logout': RouteRecordInfo<'logout', '/logout', Record<never, never>, Record<never, never>>,
    '/my-applications/': RouteRecordInfo<'/my-applications/', '/my-applications', Record<never, never>, Record<never, never>>,
    '/profiles/': RouteRecordInfo<'/profiles/', '/profiles', Record<never, never>, Record<never, never>>,
    '/recipe-wrangler/': RouteRecordInfo<'/recipe-wrangler/', '/recipe-wrangler', Record<never, never>, Record<never, never>>,
    'signup': RouteRecordInfo<'signup', '/signup', Record<never, never>, Record<never, never>>,
    '/user/[userId]/profile/': RouteRecordInfo<'/user/[userId]/profile/', '/user/:userId/profile', { userId: ParamValue<true> }, { userId: ParamValue<false> }>,
  }
}
